# create a cluster of chunkservers
version: "3"

services:
  chunkserver0:
    image: chunkserver
    network_mode: host
    volumes:
      - "./chunk0:/src/chunk"
    command:
      - "-m"
      - "chunk"
      - "-p"
      - "2181"
  chunkserver1:
    image: chunkserver
    network_mode: host
    volumes:
      - "./chunk1:/src/chunk"
    command:
      - "-m"
      - "chunk"
      - "-p"
      - "2182"
  chunkserver2:
    image: chunkserver
    network_mode: host
    volumes:
      - "./chunk2:/src/chunk"
    command:
      - "-m"
      - "chunk"
      - "-p"
      - "2183"
  chunkserver3:
    image: chunkserver
    network_mode: host
    volumes:
      - "./chunk3:/src/chunk"
    command:
      - "-m"
      - "chunk"
      - "-p"
      - "2184"
  chunkserver4:
    image: chunkserver
    network_mode: host
    volumes:
      - "./chunk4:/src/chunk"
    command:
      - "-m"
      - "chunk"
      - "-p"
      - "2185"
