# create a cluster of chunkservers
version: '3'

services:
  chunkserver0:
    image: seanchao/chunkserver
    ports:
      - '2181:10000'
    command:
      - '-m'
      - 'chunk'
      - '-p'
      - '10000'
  chunkserver1:
    image: seanchao/chunkserver
    ports:
      - '2182:10000'
    command:
      - '-m'
      - 'chunk'
      - '-p'
      - '10000'
  chunkserver2:
    image: seanchao/chunkserver
    ports:
      - '2183:10000'
    command:
      - '-m'
      - 'chunk'
      - '-p'
      - '10000'
  chunkserver3:
    image: seanchao/chunkserver
    ports:
      - '2184:10000'
    command:
      - '-m'
      - 'chunk'
      - '-p'
      - '10000'
  chunkserver4:
    image: seanchao/chunkserver
    ports:
      - '2185:10000'
    command:
      - '-m'
      - 'chunk'
      - '-p'
      - '10000'