/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.alittlela;

import org.apache.commons.cli.*;

import static org.alittlela.util.Random.randomPort;

public class App {
    public static AppConfig parseArgs(String[] args) {
        Options options = new Options();

        Option modeOpt =
                new Option(
                        "m",
                        "mode",
                        true,
                        "run in master mode (master) or chunk server mode (chunk)");
        modeOpt.setRequired(true);
        options.addOption(modeOpt);

        options.addOption("p", "port", true, "listening port");


        CommandLineParser parser = new DefaultParser();
        HelpFormatter formatter = new HelpFormatter();
        CommandLine cmd = null;

        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            formatter.printHelp("dfs -m master|chunk", options);
            System.exit(1);
        }
        AppMode appMode;
        String mode = cmd.getOptionValue("mode");
        if (mode.equals("master"))
            appMode = AppMode.MASTER;
        else if (mode.equals("chunk"))
            appMode = AppMode.CHUNK_SERVER;
        else
            throw new IllegalArgumentException("Invalid DFS mode: " + mode);
        System.out.println("port: " + cmd.getOptionValue("port"));
        String portStr = cmd.getOptionValue("port");
        int port = (portStr != null) ? Integer.parseInt(portStr) : randomPort(10000);
        return new AppConfig(appMode, port);
    }

    public static void main(String[] args) {
        AppConfig appConfig = parseArgs(args);
        new App().run(appConfig);
    }

    public void runMaster() {
        // TODO:
        try {
            HelloWorldServer.main(new String[]{});
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void runChunkServer(ChunkServer.ChunkServerConfig config) {
        // TODO:
        try {
            ChunkServer cs = new ChunkServer();
            cs.run(config);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void run(AppConfig appConfig) {
        switch (appConfig.mode) {
            case MASTER:
                runMaster();
                break;
            case CHUNK_SERVER:
                ChunkServer.ChunkServerConfig config = new ChunkServer.ChunkServerConfig(appConfig.port);
                runChunkServer(config);
                break;

            default:
                break;
        }
    }

    public enum AppMode {MASTER, CHUNK_SERVER}

    record AppConfig(
            AppMode mode,
            int port
    ) {
    }
}
